package classes;

public enum EMapType {
	
	SOLG, SOLM, SOLD, TERREG, TERREM, TERRED, PLATFORMEHG, PLATFORMEHD, PLATFORMEBG, PLATFORMEBD,EMPTY, BRIQUE, IDLE, IDLE2, PLATFORMEM, PLATFORMED, PLATFORMEG, PLATFORME, BOISG, BOISD, BOISV, BOISH, COTEVG, COTEVD, COTEB, COTE1, COTE2, COTE3, COTE4, COTE5, COTE6,APPLE;
	
}
